import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bindi's Cupcakery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <h1>Navbar</h1>
        </div>
        {children}
        <div>
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
