"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import useLenis from "@/hooks/useLenis";
// export const metadata: Metadata = {
//   title: "Bindi's Cupcakery",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useLenis();
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar />
          <div data-scroll-container>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
